extVault:
  enabled: false

extSecret:
  enabled: true
  secretStore: ott-prod-ss
  vaultKey: fptplay-nis-realtime-config
  refreshInterval: 5m
  defaultMode: 644
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/source/config.js"
    subPath: config.js
    readOnly: true

customSecret:
  enabled: false
  defaultMode: 644
  secretName: fptplay-nis-realtime
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/source/config.js"
    subPath: config.js
    readOnly: true

customCM:
  enabled: false
  defaultMode: 644
  cmName:
  osEnv:
    enabled: false
  values:
    .env: |
      key=values
      test=test
      sdf=fsdf
    .config: |
      tst=sdf
      sdfsdf=sdf
  volumeMount:
  - mountPath: "/api-tracking-2.0/test/.env"
    subPath: .env
    readOnly: true
  - mountPath: "/api-tracking-2.0/test/.config"
    subPath: .config
    readOnly: true
