extVault:
  enabled: false

extSecret:
  enabled: true
  secretStore: mdbd
  vaultKey: upload-service
  refreshInterval: 5m
  defaultMode: 644
  osEnv:
    enabled: true
  volumeMount:
  - mountPath: "/build/adsplay-server/start-server.sh"
    subPath: start-server.sh
    readOnly: true

customSecret:
  enabled: false
  defaultMode: 644
  secretName: auth-secret
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/ads-tracking-2.0/test/auth"
    subPath: auth
    readOnly: true

customCM:
  enabled: false
  defaultMode: 644
  cmName:
  osEnv:
    enabled: false
  values:
    .env: |
      key=values
      test=test
      sdf=fsdf
    .config: |
      tst=sdf
      sdfsdf=sdf
  volumeMount:
  - mountPath: "/ads-tracking-2.0/test/.env"
    subPath: .env
    readOnly: true
  - mountPath: "/ads-tracking-2.0/test/.config"
    subPath: .config
    readOnly: true