apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mdbd-admin-web-prod
  labels:
    project: default
  annotations:
    argocd-image-updater.argoproj.io/git-branch: ott-prod
    argocd-image-updater.argoproj.io/image-list: mdbd=docker-registry.fbox.fpt.vn/dsc/mdbd-admin-web
    argocd-image-updater.argoproj.io/mdbd.force-update: 'true'
    argocd-image-updater.argoproj.io/mdbd.allow-tags: regexp:dev-.*$
    argocd-image-updater.argoproj.io/mdbd.pull-secret: pullsecret:argo-cd/docker-registry.fbox.fpt.vn
    argocd-image-updater.argoproj.io/mdbd.update-strategy: latest
    argocd-image-updater.argoproj.io/mdbd.helm.image-name: deployment.repository
    argocd-image-updater.argoproj.io/mdbd.helm.image-tag: deployment.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argo-cd/git-creds
spec:
  project: default
  destination:
    namespace: mdbd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://git.fpt.net/fpl/he-thong/devops/cicd-template.git
    path: manifest
    targetRevision: ott-prod
    helm:
      valueFiles:
      - values/mdbd/admin-web/deployment.yml
      - values/mdbd/admin-web/healthcheck.yml
      - values/mdbd/admin-web/ingress.yml
      - values/mdbd/admin-web/cronjob.yml
      - values/mdbd/admin-web/secret.yml
      - values/mdbd/admin-web/volumes.yml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true