extVault:
  enabled: false

extSecret:
  enabled: false
  secretStore: ott-prod-ss
  vaultKey: 
  refreshInterval: 20m
  defaultMode: 644
  osEnv:
    enabled: true
  volumeMount: []

customSecret:
  enabled: false
  defaultMode: 644
  secretName: auth-secret
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/home/test/auth"
    subPath: username.yml
    readOnly: true

customCM:
  enabled: false
  defaultMode: 644
  cmName:
  osEnv:
    enabled: false
  values:
    .env: |
      key=values
      test=test
      sdf=fsdf
    .config: |
      tst=sdf
      sdfsdf=sdf
  volumeMount:
  - mountPath: "/home/test/.env"
    subPath: .env
    readOnly: true
  - mountPath: "/home/test/.config"
    subPath: .config
    readOnly: true