extVault:
  enabled: false

extSecret:
  enabled: true
  secretStore: smarthome-prod
  vaultKey: smarthome-consumer-engagements
  refreshInterval: 5m
  defaultMode: 644
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/app/.env"
    subPath: .env
    readOnly: true

customSecret:
  enabled: false
  defaultMode: 644
  secretName: auth-secret
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/web-fptplay/test/auth"
    subPath: auth
    readOnly: true

customCM:
  enabled: false
  defaultMode: 644
  cmName:
  osEnv:
    enabled: false
  values:
    .env: |
      key=values
      test=test
      sdf=fsdf
    .config: |
      tst=sdf
      sdfsdf=sdf
  volumeMount:
  - mountPath: "/web-fptplay/test/.env"
    subPath: .env
    readOnly: true
  - mountPath: "/web-fptplay/test/.config"
    subPath: .config
    readOnly: true