aws_access_key = "input"
aws_secret_key = "inout"
key_name = "lab"
private_key_path = "./private-key.pem"
region = "ap-southeast-1"
billing_code_tag = "0939473498"
enviroment_tag = "dev"
bucket_name_prefix = "day03-s3"
