{{- if .Values.extVault.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding-{{ .Values.global.appName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
{{- end }}

---
{{- $appName := .Values.global.appName }}
{{- with $.Values.extSecret }}
{{- if .enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $appName }}
spec:
  refreshInterval: {{ .refreshInterval | default "5m" }}
  secretStoreRef:
    name: {{ .secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ $appName }}-ext
  dataFrom:
  - extract:
      key: {{ .vaultKey }}
{{- end }}
{{- end }}