cronjob:
  enabled: false
  useVolumes: false
  schedule: 0 22 * * *
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 2
  suspend: false
  image:
    repository: harbor.fptplay.net/fplay-api/debit-t90
    tag: debit_t90-build-75789
    pullSecrets: harbor.fptplay.net
  restartPolicy: OnFailure
  resources:
    enabled: true
    requests:
      cpu: 1000m
      memory: 1000Mi
    limits:
      cpu: 2000m
      memory: 2000Mi
  command: '/bin/sh'
  args:
  - "-c"
  - "curl"
  env:
  - name: fd
    value: sdfsd
  enableProxy:
    enabled: true
    httpProxy: "http://proxy.hcm.fpt.vn:80"
    httpsProxy: "http://proxy.hcm.fpt.vn:80"
    noProxy: "localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,.svc,.cluster.local,172.0.0.0/8,*.fptplay.net,git.fpt.net"

job:
  enabled: true
  useVolumes: false
  hook: PostSync
  deleteHook: HookSucceeded
  backoffLimit: 4
  parallelism: 1
  hostAliases:
  - ip: "183.81.83.9"
    hostnames:
    - "ansible-awx.fptplay.net"
  image:
    repository: curlimages/curl
    tag: latest
    pullSecrets:
  command: "/bin/sh"
  args: 
  - "-c"
  - "curl --location --request POST 'https://ansible-awx.fptplay.net/api/v2/job_templates/15/launch/' --header 'Content-Type: application/json' --header 'Authorization: Bearer J7sQgBM7nBEBf5gO3Vs0FVfahLhOb6' --data-raw '{\"extra_vars\": {\"path\":\"/mnt/cacheweb/smarttv-shop\"}}'"
  restartPolicy: Never
  resources:
    enabled: true
    requests:
      cpu: 1000m
      memory: 1000Mi
    limits:
      cpu: 2000m
      memory: 2000Mi
  env: []
  enableProxy:
    enabled: true
    httpProxy: "http://proxy.hcm.fpt.vn:80"
    httpsProxy: "http://proxy.hcm.fpt.vn:80"
    noProxy: "localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,.svc,.cluster.local,172.0.0.0/8,.fptplay.net,git.fpt.net"