apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: deployment
  annotations:
    argocd-image-updater.argoproj.io/git-branch: ott-prod
    argocd-image-updater.argoproj.io/image-list: myimage=harbor.fptplay.net/fplay-api/fptplay-recommendation-crontab-lps
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
    argocd-image-updater.argoproj.io/myimage.allow-tags: regexp:^cron-sync-lps-.*$
    argocd-image-updater.argoproj.io/myimage.pull-secret: secret:argo-cd/harbor-ott#credential
    argocd-image-updater.argoproj.io/myimage.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: ' git:secret:argo-cd/git-creds'
    argocd-image-updater.argoproj.io/myimage.helm.image-name: cronjob.image.repository
    argocd-image-updater.argoproj.io/myimage.helm.image-tag: cronjob.image.tag
    notifications.argoproj.io/subscribe.out-of-sync.telegram: "-987170400"
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-987170400"
  name: api-cronjob-fptplay-recommendation-crontab-lps
spec:
  destination:
    namespace: api
    server: https://kubernetes.default.svc
  project: api
  source:
    helm:
      valueFiles:
      - values/api/cronjob-fptplay-recommendation-lps/deployment.yaml
      - values/api/cronjob-fptplay-recommendation-lps/healthcheck.yaml
      - values/api/cronjob-fptplay-recommendation-lps/ingress.yaml
      - values/api/cronjob-fptplay-recommendation-lps/cronjob.yaml
      - values/api/cronjob-fptplay-recommendation-lps/secret.yaml
      - values/api/cronjob-fptplay-recommendation-lps/volumes.yaml
    path: manifest
    repoURL: https://git.fpt.net/fpl/he-thong/devops/cicd-template.git
    targetRevision: ott-prod
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
