apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ads-gateway-isc-prod
  labels:
    project: ads
  annotations:
    argocd-image-updater.argoproj.io/git-branch: ott-prod
    argocd-image-updater.argoproj.io/image-list: ads=docker-registry.fbox.fpt.vn/ads/ads-gateway-isc
    argocd-image-updater.argoproj.io/ads.force-update: 'true'
    argocd-image-updater.argoproj.io/ads.allow-tags: regexp:^master-.*$
    argocd-image-updater.argoproj.io/ads.pull-secret: pullsecret:argo-cd/docker-registry.fbox.fpt.vn
    argocd-image-updater.argoproj.io/ads.update-strategy: latest
    argocd-image-updater.argoproj.io/ads.helm.image-name: deployment.repository
    argocd-image-updater.argoproj.io/ads.helm.image-tag: deployment.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argo-cd/git-creds
spec:
  project: ads
  destination:
    namespace: ads
    server: https://kubernetes.default.svc
  source:
    repoURL: https://git.fpt.net/fpl/he-thong/devops/cicd-template.git
    path: manifest
    targetRevision: ott-prod
    helm:
      valueFiles:
      - values/ads/gateway-isc/deployment.yml
      - values/ads/gateway-isc/healthcheck.yml
      - values/ads/gateway-isc/ingress.yml
      - values/ads/gateway-isc/cronjob.yml
      - values/ads/gateway-isc/secret.yml
      - values/ads/gateway-isc/volumes.yml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true