apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ads-wifi-delivery-v2-fw
  labels:
    project: ads
  annotations:
    argocd-image-updater.argoproj.io/git-branch: ott-prod
    argocd-image-updater.argoproj.io/image-list: ads=harbor.fptplay.net/fplay-ads/ads-wifi-delivery-v2
    argocd-image-updater.argoproj.io/ads.force-update: 'true'
    argocd-image-updater.argoproj.io/ads.allow-tags: regexp:master-.*$
    argocd-image-updater.argoproj.io/ads.pull-secret: pullsecret:argo-cd/harbor.fptplay.net
    argocd-image-updater.argoproj.io/ads.update-strategy: latest
    argocd-image-updater.argoproj.io/ads.helm.image-name: deployment.repository
    argocd-image-updater.argoproj.io/ads.helm.image-tag: deployment.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argo-cd/git.fpt.net
spec:
  project: ads
  destination:
    namespace: ads
    server: https://kubernetes.default.svc
  source:
    repoURL: https://git.fpt.net/fpl/he-thong/devops/cicd-template.git
    path: manifest
    targetRevision: ott-prod
    helm:
      valueFiles:
      - values/ads/wifi-delivery-v2-fw/deployment.yml
      - values/ads/wifi-delivery-v2-fw/healthcheck.yml
      - values/ads/wifi-delivery-v2-fw/ingress.yml
      - values/ads/wifi-delivery-v2-fw/cronjob.yml
      - values/ads/wifi-delivery-v2-fw/secret.yml
      - values/ads/wifi-delivery-v2-fw/volumes.yml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true