global:
  appName: finside-prod
  serviceGroup: api
  labels: []
  annotations: []
  hostAliases:
  - ip: "42.117.9.173"
    hostnames:
    - "iapi02.fptplay.net"
    - "iapi.fptplay.net.vn"
  - ip: "42.119.252.82"
    hostnames:
    - "iapi-kplus.fptplay.net"
  - ip: "172.20.2.250"
    hostnames:
    - "upload-image.fptplay.net"
  - ip: "118.69.184.28"
    hostnames:
    - "ingestion.fptplay.net"
  env: []

deployment:
  enabled: true
  repository: docker-registry.fbox.fpt.vn/api/finside
  tag: master-build-109512
  replicaCount: 2
  revisionHistoryLimit: 5
  pullPolicy: IfNotPresent
  pullSecret: docker-registry.fbox.fpt.vn
  serviceAccount: default
  restartPolicy: Always

service:
  enabled: true
  type: ClusterIP
  multiPort: false
  ports:
  - port: 5011
    targetPort: 5011
    nodePort: []
    hostPort: []
    protocol: TCP

initContainer:
- name: sysctl-init
  image: docker-registry.fbox.fpt.vn/tools/busybox
  command:
  - /bin/sh
  - -c
  - |
    sysctl -w net.core.somaxconn=60000
  securityContext:
    privileged: true

strategy:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 50%

resources:
  requests:
    cpu: 1000m
    memory: 1024Mi
  limits: 
    cpu: 8000m
    memory: 8000Mi

enableProxy:
  enabled: true
  httpProxy: "http://proxy.hcm.fpt.vn:80"
  httpsProxy: "http://proxy.hcm.fpt.vn:80"
  noProxy: "localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,git.fpt.net, .svc, .svc.cluster.local,.fptplay.net, .fptplay.net.vn"

autoscaling:
  enabled: false
  minReplicas: 8
  maxReplicas: 16
  targetCPU: 150
  targetMemory:
  
  behavior:
    enabled: false
    scaleDown:
      enabled: true
      pods:
        periodSeconds: 20
        value: 1
      percent:
        periodSeconds: 20
        value: 10
      selectPolicy: Max
      stabilizationWindowSeconds: 10

    scaleUp:
      enabled: true
      pods:
        periodSeconds: 20
        value: 2
      percent: 
        periodSeconds: 20
        value: 50
      selectPolicy: Max
      stabilizationWindowSeconds: 10

affinity:
  enabled: false
  podAntiAffinity:
    enabled: true
    soft:
      enabled: false 
    weight: 100
    key: app
    operator: In
    values:
    - cache-manager
    topologyKey: "kubernetes.io/hostname"

  podAffinity:
    enabled: false
    soft:
      enabled: false 
    weight:
    key: 
    operator: 
    values: []
    topologyKey: []

  nodeAffinity:
    enabled: false
    soft:
      enabled: false
    values:
    - weight: 50
      preference:
        matchExpressions:
        - key:
          operator:
          values:
