extVault:
  enabled: false

extSecret:
  enabled: true
  secretStore: cms-prod
  vaultKey: api-sport-env
  refreshInterval: 5m
  defaultMode: 644
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/src/.env"
    subPath: .env
    readOnly: true

customSecret:
  enabled: false
  defaultMode: 644
  secretName: auth-secret
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/api-sport/test/auth"
    subPath: auth
    readOnly: true

customCM:
  enabled: false
  defaultMode: 644
  cmName:
  osEnv:
    enabled: false
  values:
    .env: |
      key=values
      test=test
      sdf=fsdf
    .config: |
      tst=sdf
      sdfsdf=sdf
  volumeMount:
  - mountPath: "/api-sport/test/.env"
    subPath: .env
    readOnly: true
  - mountPath: "/api-sport/test/.config"
    subPath: .config
    readOnly: true