global:
  appName: w2w-prod
  serviceGroup: api
  labels: []
  annotations: []
  hostAliases: []
  env: []

deployment:
  enabled: false
  repository: harbor.fptplay.net/fplay-ads/ads-cdn-delivery-v1
  tag: master-build-83691
  replicaCount: 10
  revisionHistoryLimit: 10
  pullPolicy: IfNotPresent
  pullSecret: harbor.fptplay.net
  serviceAccount: default
  restartPolicy: Always

service:
  enabled: false
  type: ClusterIP
  multiPort: false
  ports:
  - port: 80
    targetPort: 8089
    nodePort: []
    hostPort: []
    protocol: TCP

initContainer:
- name: sysctl-init
  image: busybox
  command:
  - /bin/sh
  - -c
  - |
    sysctl -w net.core.somaxconn=60000
  securityContext:
    privileged: true

strategy:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 50%

resources:
  requests:
    cpu: 1000m
    memory: 1000Mi
  limits: 
    cpu: 2000m
    memory: 2000Mi

enableProxy:
  enabled: true
  httpProxy: "http://proxy.hcm.fpt.vn:80"
  httpsProxy: "http://proxy.hcm.fpt.vn:80"
  noProxy: "localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,.svc,.cluster.local,172.0.0.0/8,*.fptplay.net,git.fpt.net"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPU: 90
  targetMemory: 400
  
  behavior:
    enabled: false
    scaleDown:
      enabled: true
      pods:
        periodSeconds: 20
        value: 1
      percent:
        periodSeconds: 20
        value: 10
      selectPolicy: Max
      stabilizationWindowSeconds: 10

    scaleUp:
      enabled: true
      pods:
        periodSeconds: 20
        value: 2
      percent: 
        periodSeconds: 20
        value: 50
      selectPolicy: Max
      stabilizationWindowSeconds: 10

affinity:
  enabled: false
  podAntiAffinity:
    enabled: true
    soft:
      enabled: false 
    weight: 100
    key: app
    operator: In
    values:
    - cache-manager
    topologyKey: "kubernetes.io/hostname"

  podAffinity:
    enabled: false
    soft:
      enabled: false 
    weight:
    key: 
    operator: 
    values: []
    topologyKey: []

  nodeAffinity:
    enabled: false
    soft:
      enabled: false
    values:
    - weight: 50
      preference:
        matchExpressions:
        - key:
          operator:
          values:
