extVault:
  enabled: false

extSecret:
  enabled: true
  secretStore: ads-prod
  vaultKey: gateway-survey
  refreshInterval: 5m
  defaultMode: 644
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/ads-gateway-survey/startup.sh"
    subPath: startup.sh
    readOnly: true
  - mountPath: "/ads-gateway-survey/conf/core_config.json"
    subPath: core_config.json
    readOnly: true
  - mountPath: "/ads-gateway-survey/conf/gateway.json"
    subPath: gateway.json
    readOnly: true
  - mountPath: "/ads-gateway-survey/conf/data_manager.json"
    subPath: data_manager.json
    readOnly: true

customSecret:
  enabled: false
  defaultMode: 644
  secretName: auth-secret
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/ads-tracking-2.0/test/auth"
    subPath: auth
    readOnly: true

customCM:
  enabled: false
  defaultMode: 644
  cmName:
  osEnv:
    enabled: false
  values:
    .env: |
      key=values
      test=test
      sdf=fsdf
    .config: |
      tst=sdf
      sdfsdf=sdf
  volumeMount:
  - mountPath: "/ads-tracking-2.0/test/.env"
    subPath: .env
    readOnly: true
  - mountPath: "/ads-tracking-2.0/test/.config"
    subPath: .config
    readOnly: true