apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: deployment
  annotations:
    argocd-image-updater.argoproj.io/git-branch: ott-prod
    argocd-image-updater.argoproj.io/image-list: myimage=docker-registry.fbox.fpt.vn/image-base/weinre
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
    argocd-image-updater.argoproj.io/myimage.allow-tags: regexp:^latest-.*$
    argocd-image-updater.argoproj.io/myimage.pull-secret: secret:argo-cd/harbor-ott#credential
    argocd-image-updater.argoproj.io/myimage.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: ' git:secret:argo-cd/git-creds'
    argocd-image-updater.argoproj.io/myimage.helm.image-name: cronjob.image.repository
    argocd-image-updater.argoproj.io/myimage.helm.image-tag: cronjob.image.tag
    notifications.argoproj.io/subscribe.out-of-sync.telegram: "-987170400"
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-987170400"
  name: smarttv-debug-smarttv-prod-fpl
spec:
  destination:
    namespace: smarttv
    server: https://kubernetes.default.svc
  project: smarttv
  source:
    helm:
      valueFiles:
      - values/smarttv/debug-smarttv/deployment.yaml
      - values/smarttv/debug-smarttv/healthcheck.yaml
      - values/smarttv/debug-smarttv/ingress.yaml
      - values/smarttv/debug-smarttv/cronjob.yaml
      - values/smarttv/debug-smarttv/secret.yaml
      - values/smarttv/debug-smarttv/volumes.yaml
    path: manifest
    repoURL: https://git.fpt.net/fpl/he-thong/devops/cicd-template.git
    targetRevision: ott-prod
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
