apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: deployment
  annotations:
    argocd-image-updater.argoproj.io/git-branch: ott-prod
    argocd-image-updater.argoproj.io/image-list: myimage=docker-registry.fbox.fpt.vn/smarttv/smarttv-shoppertainment
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
    argocd-image-updater.argoproj.io/myimage.allow-tags: regexp:^master-.*$
    argocd-image-updater.argoproj.io/myimage.pull-secret: secret:argo-cd/harbor-ott#credential
    argocd-image-updater.argoproj.io/myimage.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: ' git:secret:argo-cd/git-creds'
    argocd-image-updater.argoproj.io/myimage.helm.image-name: deployment.repository
    argocd-image-updater.argoproj.io/myimage.helm.image-tag: deployment.tag
    notifications.argoproj.io/subscribe.out-of-sync.telegram: "-987170400"
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-987170400"
  name: smarttv-shoppertainment-prod
spec:
  destination:
    namespace: smarttv
    server: https://kubernetes.default.svc
  project: smarttv
  source:
    helm:
      valueFiles:
      - values/smarttv/smarttv-shoppertainment/deployment.yaml
      - values/smarttv/smarttv-shoppertainment/healthcheck.yaml
      - values/smarttv/smarttv-shoppertainment/ingress.yaml
      - values/smarttv/smarttv-shoppertainment/cronjob.yaml
      - values/smarttv/smarttv-shoppertainment/secret.yaml
      - values/smarttv/smarttv-shoppertainment/volumes.yaml
    path: manifest
    repoURL: https://git.fpt.net/fpl/he-thong/devops/cicd-template.git
    targetRevision: ott-prod
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
