extVault:
  enabled: false

extSecret:
  enabled: true
  secretStore: web-prod
  vaultKey: web-fptplaytv-config
  refreshInterval: 5m
  defaultMode: 644
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/source/application/config/production/database.php"
    subPath: database.php
    readOnly: true

customSecret:
  enabled: false
  defaultMode: 644
  secretName: auth-secret
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/web-fptplaytv/test/auth"
    subPath: auth
    readOnly: true

customCM:
  enabled: false
  defaultMode: 644
  cmName:
  osEnv:
    enabled: false
  values:
    .env: |
      key=values
      test=test
      sdf=fsdf
    .config: |
      tst=sdf
      sdfsdf=sdf
  volumeMount:
  - mountPath: "/web-fptplaytv/test/.env"
    subPath: .env
    readOnly: true
  - mountPath: "/web-fptplaytv/test/.config"
    subPath: .config
    readOnly: true