extVault:
  enabled: false

extSecret:
  enabled: false
  secretStore: ott-prod-ss
  vaultKey: api-google-c2c-env
  refreshInterval: 20m
  defaultMode: 644
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: /source/.env
    name: env-vault
    readOnly: true
    subPath: .env
  - mountPath: /source/credentials.json
    name: env-vault
    readOnly: true
    subPath: credentials.json

customSecret:
  enabled: false
  defaultMode: 644
  secretName: auth-secret
  osEnv:
    enabled: false
  volumeMount:
  - mountPath: "/ads-tracking-2.0/test/auth"
    subPath: auth
    readOnly: true

customCM:
  enabled: false
  defaultMode: 644
  cmName:
  osEnv:
    enabled: false
  values:
    .env: |
      key=values
      test=test
      sdf=fsdf
    .config: |
      tst=sdf
      sdfsdf=sdf
  volumeMount:
  - mountPath: "/ads-tracking-2.0/test/.env"
    subPath: .env
    readOnly: true
  - mountPath: "/ads-tracking-2.0/test/.config"
    subPath: .config
    readOnly: true
